# Execute command: docker-compose up -d
# Description: Docker-compose file to run the backend and frontend services

# version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:5002"  
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"  
    env_file:
      - .env  
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongodb_data: